Men Without Women stories added for public domain day
standardebooks/ernest-hemingway_short-fiction pull request #1
Opened 2023-01-01 17:04 UTC by maticstric

2023-01-01 22:18 UTC, acabal requested changes
Looks great! Just a few minor notes in the CSS.

2023-01-01 22:18 UTC, acabal commented on src/epub/css/core.css
> -ol,
Please add these back in as they are part of the new template. Thanks

2023-01-01 22:18 UTC, acabal commented on src/epub/css/local.css
> +	text-align: center;
text-align: center is not necessary because header gets that from core.css

2023-01-02 04:40 UTC, maticstric commented
Should be done!

2023-01-02 04:41 UTC, merged

2023-01-02 04:41 UTC, acabal commented
Excellent, thanks!